### ISSUE TITLE
Latest version 6.8.13 cannot play titles with utf-8 characters

### ISSUE THREAD

**Issue by muelli01** [anxdpanic/plugin.video.youtube#136]
After installing Version 6.8.13 because of the "no stream error" with prior Version, i now can not play titles that have UTF8 special characters in the title like ß or ä etc.

Log file shows:

19:40:48.469 T:1542976416   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'utf8' codec can't decode byte 0xdf in position 8: invalid continuation byte
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 105, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 767, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 104, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 515, in load_stream_infos
                                                return self._method_get_video_info(video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 772, in _method_get_video_info
                                                meta_info['video']['title'] = meta_info['video']['title'].decode('utf-8')
                                              File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0xdf in position 8: invalid continuation byte
                                            -->End of Python script error report<--
19:40:48.592 T:1945600000   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=TJ7FX0A3yTU]

I hope this report helps debugging. Thanks!

**Comment by anxdpanic** [comment]
Thanks for the report, https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.8.14

**Comment by momobonavetti** [comment]
I was about to report the same issue, and it was already fixed! Great job, guys!

**Comment by wikt0r** [comment]
I still get this error with 6.8.17. 

`2021-09-28 16:43:17.843 T:140062156531264   DEBUG: [plugin.video.youtube] User is logged in
2021-09-28 16:43:18.856 T:140062156531264   DEBUG: [plugin.video.youtube] Subtitle get_subtitles: for setting |1|
2021-09-28 16:43:18.860 T:140062156531264   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'utf8' codec can't decode byte 0xe9 in position 22: invalid continuation byte
                                            Traceback (most recent call last):
                                              File "/home/wiktor/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/home/wiktor/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/wiktor/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/home/wiktor/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 105, in navigate
                                                result = method(context, re_match)
                                              File "/home/wiktor/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/wiktor/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 767, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/home/wiktor/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/home/wiktor/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 104, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id)
                                              File "/home/wiktor/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 537, in load_stream_infos
                                                return self._method_get_video_info(video_id)
                                              File "/home/wiktor/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 900, in _method_get_video_info
                                                meta_info['subtitles'] = Subtitles(self._context, video_id, captions).get_subtitles()
                                              File "/home/wiktor/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/subtitles.py", line 125, in get_subtitles
                                                return self._prompt()
                                              File "/home/wiktor/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/subtitles.py", line 144, in _prompt
                                                tracks = [(track.get('languageCode'), self._get_language_name(track)) for track in self.caption_tracks]
                                              File "/home/wiktor/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/subtitles.py", line 231, in _get_language_name
                                                return self._decode_language_name(lang_name)
                                              File "/home/wiktor/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/subtitles.py", line 240, in _decode_language_name
                                                language_name = language_name.decode('utf-8')
                                              File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
                                                return codecs.utf_8_decode(input, errors, True)
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 22: invalid continuation byte
                                            -->End of Python script error report<--
2021-09-28 16:43:18.862 T:140062156531264   DEBUG: onExecutionDone(50, /home/wiktor/.kodi/addons/plugin.video.youtube/resources/lib/default.py)
2021-09-28 16:43:18.880 T:140062755019456   DEBUG: ------ Window Init (DialogNotification.xml) ------
2021-09-28 16:43:19.080 T:140062156531264    INFO: Python interpreter stopped
2021-09-28 16:43:19.081 T:140062156531264   DEBUG: Thread LanguageInvoker 140062156531264 terminating
2021-09-28 16:43:19.090 T:140062080398912   DEBUG: Thread scriptobs 140062080398912 terminating
2021-09-28 16:43:19.091 T:140062755019456   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2021-09-28 16:43:19.091 T:140062755019456   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=FnfryZmTytI]
2021-09-28 16:43:19.092 T:140062755019456   DEBUG: Playlist Player: one or more items failed to play... aborting playback
`
