### ISSUE TITLE
'My Subscriptions' fails to load and causes error in 6.8.21

### ISSUE THREAD

**Issue by reven** [anxdpanic/plugin.video.youtube#368]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.21
* Kodi Version: 19.4.0
* Kodi GUI Language: English
* Operating System: Ubuntu 22.04.1
* Operating System Language: English

------

### Expected Behavior

Before update to latest version, My subscriptions would load current subscriptions from YouTube.

------

### Current Behavior

No videos load. Trying to go back to the top level menu sometimes causes a crash of the plugin. Search and other options still work, so API is correct and connected/authorized properly.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open plugin
2. Go to "My Subscriptions"
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).
```
2022-12-04 17:02:59.593 T:1187599    INFO <general>: [plugin.video.youtube] Running: YouTube (6.8.21+matrix.1) on Matrix (Kodi-19.4) with Python 3.10.6
                                                   	Path: /
                                                   	Params: {}
2022-12-04 17:02:59.597 T:1187599 WARNING <CSettingsManager>: unable to read value of setting "kodion.content.max_per_page"
2022-12-04 17:02:59.598 T:1187599 WARNING <CAddonSettings[plugin.video.youtube]>: failed to load value "50" for setting kodion.content.max_per_page
2022-12-04 17:02:59.605 T:1187599   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'sqlite3.OperationalError'>
                                                   Error Contents: cannot start a transaction within a transaction
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                       runner.run(__provider__)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                       __RUNNER__.run(provider, context)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 34, in run
                                                       results = provider.navigate(context)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 124, in navigate
                                                       result = method(context, re_match)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 157, in _internal_root
                                                       return self.on_root(context, re_match)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 1697, in on_root
                                                       if settings.get_bool('youtube.folder.tags.show', True) and (len(tags.get_channels('')) > 0):
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/tags.py", line 66, in get_channels
                                                       cur.execute("begin")
                                                   sqlite3.OperationalError: cannot start a transaction within a transaction
                                                   -->End of Python script error report<--
                                                   
2022-12-04 17:02:59.629 T:1841     INFO <general>: PulseAudio: Opened device alsa_output.pci-0000_07_00.1.hdmi-stereo in pcm mode with Buffersize 150 ms Periodsize 50 ms
2022-12-04 17:02:59.673 T:1187599    INFO <general>: Python interpreter stopped
2022-12-04 17:02:59.692 T:1188810    INFO <general>: Skipped 2 duplicate messages..
2022-12-04 17:02:59.692 T:1188810   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.youtube/
2022-12-04 17:02:59.693 T:1682    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/) failed
2022-12-04 17:03:12.038 T:1178499 WARNING <CSettingsManager>: unable to read value of setting "kodion.content.max_per_page"
2022-12-04 17:03:12.038 T:1178499 WARNING <CAddonSettings[plugin.video.youtube]>: failed to load value "50" for setting kodion.content.max_per_page
2022-12-04 17:03:12.047 T:1178548 WARNING <CSettingsManager>: unable to read value of setting "kodion.content.max_per_page"
2022-12-04 17:03:12.047 T:1178548 WARNING <CAddonSettings[plugin.video.youtube]>: failed to load value "50" for setting kodion.content.max_per_page
2022-12-04 17:03:12.052 T:1178548 WARNING <CSettingsManager>: unable to read value of setting "kodion.content.max_per_page"
2022-12-04 17:03:12.053 T:1178548 WARNING <CAddonSettings[plugin.video.youtube]>: failed to load value "50" for setting kodion.content.max_per_page
2022-12-04 17:04:12.064 T:1178499 WARNING <CSettingsManager>: unable to read value of setting "kodion.content.max_per_page"
```

------

### Additional Information

Going into the plugin settings, under General > Items per page, doesn't allow for setting a number. It looks like it's incorrectly parsing the numbers as dates, maybe? The options are (blank), Friday, (blank), (blank), October, May, (blank), Friday, Settings. There's probably some typo in the field that gets displayed there?

------

**Comment by akb825** [comment]
This is still occurring on 6.8.22. Downgrading to 6.8.20 works around the issue.

**Comment by reven** [comment]
> This is still occurring on 6.8.22. Downgrading to 6.8.20 works around the issue.

That's good to know. Is there a way to downgrade through Kodi's GUI?

**Comment by anxdpanic** [comment]
can you try disabling Settings - Folder - Subscription Groups

**Comment by reven** [comment]
This doesn't fix the issue. Just in case: the issue is not with the "subscriptions" menu item, the issue is with "My Subscriptions", which creates a global playlist for all the subscriptions with videos ordered by date.

**Comment by reven** [comment]
I captured a complete log, in case it helps:
[kodi_youtube.log.zip](https://github.com/anxdpanic/plugin.video.youtube/files/10191623/kodi_youtube.log.zip)

**Comment by akb825** [comment]
> That's good to know. Is there a way to downgrade through Kodi's GUI?

Unfortunately no, you need to install it from the zip file.

> can you try disabling Settings - Folder - Subscription Groups

In my case it was "Subscriptions" (rather than "My Subscriptions") and disabling Subscription Groups fixes the crash.

**Comment by akb825** [comment]
While disabling Subscription Groups allows me to access the Subscriptions page, if I go to a channel and press the back button (to return to the list of subscriptions) the plugin errors out and exits back to the main Kodi menu. The following error is in the log:

```
2022-12-09 01:07:08.095 T:2454     INFO <general>: [plugin.video.youtube] Running: YouTube (6.8.22+matrix.1) on Matrix (Kodi-19.4) with Python 3.10.8
                                                        Path: /subscriptions/list/
                                                        Params: {}
2022-12-09 01:07:08.353 T:2454    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'sqlite3.OperationalError'>
                                                   Error Contents: cannot start a transaction within a transaction
                                                   Traceback (most recent call last):
                                                     File "/home/abarany/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                       runner.run(__provider__)
                                                     File "/home/abarany/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                       __RUNNER__.run(provider, context)
                                                     File "/home/abarany/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                       results = provider.navigate(context)
                                                     File "/home/abarany/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 105, in navigate
                                                       result = method(context, re_match)
                                                     File "/home/abarany/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/abarany/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 841, in _on_subscriptions
                                                       subscriptions = yt_subscriptions.process(method, self, context)
                                                     File "/home/abarany/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_subscriptions.py", line 87, in process
                                                       result.extend(_process_list(provider, context))
                                                     File "/home/abarany/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_subscriptions.py", line 24, in _process_list
                                                       result.extend(v3.response_to_items(provider, context, json_data))
                                                     File "/home/abarany/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/v3.py", line 322, in response_to_items
                                                       result.extend(_process_list_response(provider, context, json_data))
                                                     File "/home/abarany/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/v3.py", line 131, in _process_list_response
                                                       tags.create_channel(channel_id, title, item_uri, image, kind)
                                                     File "/home/abarany/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/tags.py", line 39, in create_channel
                                                       cur.execute("begin")
                                                   sqlite3.OperationalError: cannot start a transaction within a transaction
                                                   -->End of Python script error report<--
```

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/plugin.video.youtube/pull/373
next alpha should be resolved

**Comment by anxdpanic** [comment]
6.8.23 will be available soon

**Comment by reven** [comment]
Just got the 6.8.23 update and it's still not working. "My subscriptions" is either empty or shows the videos of one of the channels (chosen at random) if re-opened multiple times.

The "number of items" in the settings is fixed though.

**Comment by akb825** [comment]
I can confirm that the "Subscriptions" page at least is working again with 6.8.23.

**Comment by reven** [comment]
> I can confirm that the "Subscriptions" page at least is working again with 6.8.23.

Yes, working for me too, but it was working as well with 6.8.21 for me.

**Comment by akb825** [comment]
Weird, must either be a difference between account or subscription setups. The reverted commit has to do with tags, I haven't tagged any subscriptions or set up any groups. I also don't have a channel associated with my account, which has historically be limiting as far as YouTube features. Could also be because I'm using a custom API token rather than one of the defaults to avoid API limits.

I gave the "My Subscriptions" section a try (I normally have the folder disabled) and it seems to be working for me.

**Comment by reven** [comment]
Yes, it's definitely weird. I also did the API token setup, so it shouldn't be that. From the logs it seems that there are connection errors, but all other menus display videos and play them without issue (so it can't be a network thing).

```
2022-12-10 01:54:11.130 T:334816    INFO <general>: [plugin.video.youtube] Running: YouTube (6.8.23+matrix.1) on Matrix (Kodi-19.4) with Python 3.10.6
                                                   	Path: /
                                                   	Params: {}
2022-12-10 01:54:12.036 T:334816    INFO <general>: CPythonInvoker(7, /home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/default.py): script successfully run
2022-12-10 01:54:20.263 T:334816    INFO <general>: initializing python engine.
2022-12-10 01:54:20.264 T:334816    INFO <general>: [plugin.video.youtube] Running: YouTube (6.8.23+matrix.1) on Matrix (Kodi-19.4) with Python 3.10.6
                                                   	Path: /special/new_uploaded_videos_tv/
                                                   	Params: {}
2022-12-10 01:54:32.451 T:335924   ERROR <general>: Traceback (most recent call last):
                                                   
2022-12-10 01:54:32.451 T:335924   ERROR <general>: 
2022-12-10 01:54:32.451 T:335924   ERROR <general>:   File "/home/kodi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 703, in urlopen
                                                       httplib_response = self._make_request(
                                                   
2022-12-10 01:54:32.451 T:335924   ERROR <general>: 
2022-12-10 01:54:32.451 T:335924   ERROR <general>:   File "/home/kodi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 386, in _make_request
                                                       self._validate_conn(conn)
                                                   
2022-12-10 01:54:32.451 T:335924   ERROR <general>: 
2022-12-10 01:54:32.451 T:335924   ERROR <general>:   File "/home/kodi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 1042, in _validate_conn
                                                       conn.connect()
                                                   
2022-12-10 01:54:32.451 T:335924   ERROR <general>: 
2022-12-10 01:54:32.451 T:335924   ERROR <general>:   File "/home/kodi/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 414, in connect
                                                       self.sock = ssl_wrap_socket(
                                                   
2022-12-10 01:54:32.451 T:335924   ERROR <general>: 
2022-12-10 01:54:32.451 T:335924   ERROR <general>:   File "/home/kodi/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
                                                       ssl_sock = _ssl_wrap_socket_impl(
                                                   
2022-12-10 01:54:32.451 T:335924   ERROR <general>: 
2022-12-10 01:54:32.451 T:335924   ERROR <general>:   File "/home/kodi/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
                                                       return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
                                                   
2022-12-10 01:54:32.451 T:335924   ERROR <general>: 
2022-12-10 01:54:32.451 T:335924   ERROR <general>:   File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
                                                       return self.sslsocket_class._create(
                                                   
2022-12-10 01:54:32.451 T:335924   ERROR <general>: 
2022-12-10 01:54:32.451 T:335924   ERROR <general>:   File "/usr/lib/python3.10/ssl.py", line 1071, in _create
                                                       self.do_handshake()
                                                   
2022-12-10 01:54:32.451 T:335924   ERROR <general>: 
2022-12-10 01:54:32.451 T:335924   ERROR <general>:   File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
                                                       self._sslobj.do_handshake()
                                                   
2022-12-10 01:54:32.451 T:335924   ERROR <general>: 
2022-12-10 01:54:32.451 T:335924   ERROR <general>: ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:997)
                                                   
2022-12-10 01:54:32.451 T:335924   ERROR <general>: 
2022-12-10 01:54:32.451 T:335924   ERROR <general>: 
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   
2022-12-10 01:54:32.451 T:335924   ERROR <general>: 
2022-12-10 01:54:32.451 T:335924   ERROR <general>: Traceback (most recent call last):
                                                   
2022-12-10 01:54:32.451 T:335924   ERROR <general>: 
2022-12-10 01:54:32.452 T:335924   ERROR <general>:   File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 440, in send
                                                       resp = conn.urlopen(
                                                   
2022-12-10 01:54:32.452 T:335924   ERROR <general>: 
2022-12-10 01:54:32.452 T:335924   ERROR <general>:   File "/home/kodi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 787, in urlopen
                                                       retries = retries.increment(
                                                   
2022-12-10 01:54:32.452 T:335924   ERROR <general>: 
2022-12-10 01:54:32.452 T:335924   ERROR <general>:   File "/home/kodi/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 592, in increment
                                                       raise MaxRetryError(_pool, url, error or ResponseError(cause))
                                                   
2022-12-10 01:54:32.452 T:335924   ERROR <general>: 
2022-12-10 01:54:32.452 T:335924   ERROR <general>: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /feeds/videos.xml?channel_id=UC5UAwBUum7CPN5buc-_N1Fw (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))
                                                   
2022-12-10 01:54:32.452 T:335924   ERROR <general>: 
2022-12-10 01:54:32.452 T:335924   ERROR <general>: 
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   
2022-12-10 01:54:32.452 T:335924   ERROR <general>: 
2022-12-10 01:54:32.452 T:335924   ERROR <general>: Traceback (most recent call last):
                                                   
2022-12-10 01:54:32.452 T:335924   ERROR <general>: 
2022-12-10 01:54:32.452 T:335924   ERROR <general>:   File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 830, in fetch_xml
                                                       _response = requests.get(_url, {}, headers=headers, verify=self._verify, allow_redirects=True)
                                                   
2022-12-10 01:54:32.452 T:335924   ERROR <general>: 
2022-12-10 01:54:32.452 T:335924   ERROR <general>:   File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                       return request('get', url, params=params, **kwargs)
                                                   
2022-12-10 01:54:32.452 T:335924   ERROR <general>: 
2022-12-10 01:54:32.452 T:335924   ERROR <general>:   File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/api.py", line 61, in request
                                                       return session.request(method=method, url=url, **kwargs)
                                                   
2022-12-10 01:54:32.452 T:335924   ERROR <general>: 
2022-12-10 01:54:32.452 T:335924   ERROR <general>:   File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 529, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                   
2022-12-10 01:54:32.452 T:335924   ERROR <general>: 
2022-12-10 01:54:32.452 T:335924   ERROR <general>:   File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 645, in send
                                                       r = adapter.send(request, **kwargs)
                                                   
2022-12-10 01:54:32.452 T:335924   ERROR <general>: 
2022-12-10 01:54:32.452 T:335924   ERROR <general>:   File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 517, in send
                                                       raise SSLError(e, request=request)
                                                   
2022-12-10 01:54:32.452 T:335924   ERROR <general>: 
2022-12-10 01:54:32.452 T:335924   ERROR <general>: requests.exceptions.SSLError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /feeds/videos.xml?channel_id=UC5UAwBUum7CPN5buc-_N1Fw (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))
                                                   
[ continues like this for 6000 lines before giving up]

                                                   
2022-12-10 01:54:34.191 T:335929   ERROR <general>: 
2022-12-10 01:54:34.191 T:335929   ERROR <general>: [plugin.video.youtube] Failed |None|
2022-12-10 01:54:34.194 T:334816    INFO <general>: CPythonInvoker(7, /home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/default.py): script successfully run

```

**Comment by reven** [comment]
This issue appears as "Closed". Shall I open a new issue or how can I trouble-shoot it further?
